#!/bin/bash

echo "🔍 Checking deployment status..."

echo "📋 Step 1: Checking GitHub Actions status..."
echo "Go to: https://github.com/kunal899verma/MoviesProject/actions"
echo "Look for the latest 'Deploy to AWS' workflow"
echo ""

echo "📋 Step 2: Critical AWS resources needed:"
echo "✅ ECR Repositories (CRITICAL):"
echo "  - movie-management-backend"
echo "  - movie-management-frontend"
echo ""
echo "✅ ECS Cluster:"
echo "  - imaginary-eagle-7g4dse (already created)"
echo ""
echo "✅ Other resources:"
echo "  - CloudWatch Log Groups"
echo "  - IAM Roles"
echo "  - Secrets Manager"
echo ""

echo "📋 Step 3: Manual verification steps:"
echo "1. AWS Console → ECR → Repositories"
echo "2. Check if 'movie-management-backend' exists"
echo "3. Check if 'movie-management-frontend' exists"
echo "4. If missing, create them manually"
echo ""

echo "📋 Step 4: If ECR repositories are missing:"
echo "Create them manually:"
echo "1. AWS Console → ECR → Create repository"
echo "2. Name: movie-management-backend"
echo "3. Region: us-east-1"
echo "4. Scan on push: Enable"
echo "5. Create repository"
echo ""
echo "6. Create repository again"
echo "7. Name: movie-management-frontend"
echo "8. Region: us-east-1"
echo "9. Scan on push: Enable"
echo "10. Create repository"
echo ""

echo "🚀 After creating ECR repositories:"
echo "1. Go to GitHub Actions"
echo "2. Re-run the 'Deploy to AWS' workflow"
echo "3. Monitor deployment progress"
echo ""

echo "✅ Deployment should succeed once ECR repositories exist!"
